//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.Photogram.Model
{
    using Es.Udc.DotNet.Photogram.Model.DTOs;
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public static implicit operator ComentariosDto(Comentarios com)
        {
            ComentariosDto coment = new ComentariosDto();
            coment.Id = com.Id;
            coment.Usuario = com.Usuario;
            coment.PublicacionId = com.PublicacionId;
            coment.texto = com.texto;

            return coment;
        }
        public long Id { get; set; }
        public long Usuario { get; set; }
        public long PublicacionId { get; set; }
        public string texto { get; set; }
    
		public virtual Publicaciones Publicaciones { get; set; }
		public virtual Usuarios Usuarios { get; set; }


        public override bool Equals(Object obj)
        {
            if ((obj == null) || !this.GetType().Equals(obj.GetType()))
                return false;

            Comentarios c = (Comentarios)obj;
            return c.Id == this.Id;
        }
    }
}
