//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.Photogram.Model
{
    using Es.Udc.DotNet.Photogram.Model.DTOs;
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Comentarios = new HashSet<Comentarios>();
            this.Publicaciones = new HashSet<Publicaciones>();
            this.PublicacionesGustadas = new HashSet<Publicaciones>();
            this.Seguidores = new HashSet<Usuarios>();
            this.Seguidos = new HashSet<Usuarios>();
        }

        public static implicit operator UsuariosDto(Usuarios user)
        {
            UsuariosDto usuario = new UsuariosDto();
            usuario.usrId = user.usrId;
            usuario.loginName = user.loginName;
            usuario.name = user.name;
            usuario.password = user.password;
            usuario.pais = user.pais;
            usuario.idioma = user.idioma;
            usuario.email = user.email;
            return usuario;
        }

        public long usrId { get; set; }
        public string loginName { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string pais { get; set; }
        public string idioma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publicaciones> Publicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publicaciones> PublicacionesGustadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Seguidores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Seguidos { get; set; }
        
		public override bool Equals(Object obj)
		{
			if ((obj == null) || ! this.GetType().Equals(obj.GetType()))
				return false;
		
			Usuarios u = (Usuarios) obj;
			return u.usrId == this.usrId;
		}
    }
}
